### ISSUE TITLE
SyntaxError when running bless #{var} on template

### ISSUE THREAD

**Issue by lodyb** [marrow/cinje#22]
WebCore tutorial step using Bless #{} will return:

SyntaxError: decoding with 'cinje' codec failed (AssertionError: Unable to identify handler for line; this should be impossible!)

Test case (based on WebCore tutorial)
https://www.irccloud.com/pastebin/raw/fJubH7dP

**Comment by amcgregor** [comment]
This should have been fixed in 1.1; could you re-test with that or the latest release (1.1.1) being deployed in a few minutes?  Thanks!

**Comment by amcgregor** [comment]
Closing as fixed for now; if the issue returns, feel free to re-open!
